### PR TITLE
Implemented first version of persistence

### PR DESCRIPTION
**Pull request by jose-sanchezm**

### CODE REVIEW

**Comment by dealfonso** [comment]
Hi @jose-sanchezm 

I am testing this version and the persistence does not work. I am testing it in ubuntu 16.04, ONE 4.12 and LXC.

The logs for the VM (it is VM number 5) are the next:

```
Fri Mar 10 12:49:45 2017 [Z0][VMM][I]: ExitCode: 0
Fri Mar 10 12:49:45 2017 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Fri Mar 10 12:49:45 2017 [Z0][LCM][I]: New VM state is EPILOG
Fri Mar 10 12:49:46 2017 [Z0][TM][I]: Command execution fail: /var/lib/one/remotes/tm/onedock/mvds testonedock:/var/lib/one//datastores/0/5/disk.0 docker://testonedock:5000/dockerimage:2 5 100
Fri Mar 10 12:49:46 2017 [Z0][TM][E]: mvds: Command "docker push testonedock:5000/dockerimage:2" failed: Warning: Permanently added 'testonedock' (ECDSA) to the list of known hosts.
Fri Mar 10 12:49:46 2017 [Z0][TM][I]: Repository does not exist: testonedock:5000/dockerimage
Fri Mar 10 12:49:46 2017 [Z0][TM][E]: Error pushing saved image to testonedock:5000/dockerimage:2
Fri Mar 10 12:49:46 2017 [Z0][TM][I]: ExitCode: 1
Fri Mar 10 12:49:46 2017 [Z0][TM][E]: Error executing image transfer script: Error pushing saved image to testonedock:5000/dockerimage:2
Fri Mar 10 12:49:46 2017 [Z0][DiM][I]: New VM state is FAILED
```

It seems that it is a problem with the image. If I check the docker images (i.e. using docker images) I get the following output:

```
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry                 2                   eb3ee02bebc9        6 days ago          33.2 MB
testonedock:5000/one-3   0                   031b4db7df57        6 days ago          3.987 MB
testonedock:5000/one-0   0                   e37d367c3507        10 days ago         130 MB
testonedock:5000/one-1   0                   e37d367c3507        10 days ago         130 MB
```

The image that is being pushed to the registry (testonedock:5000/dockerimage:2) does not exist and that is why the push command fails. When I check the code (the file ```mvds```), I see that there is not any tagging for the image prior to pushing it. I think that, in order to implement the persistence, the current disk for the image (testonedock:5000/one-5:0) should be tagged to the name of the image (i.e. testonedock:5000/dockerimage:2) and then push it.

Can you please check it?

**Comment by gmolto** [comment]
Hi @jose-sanchezm. We need to decide if this PR is going to be included in the INDIGO-2 release. Please, let us know ASAP the status of the tests in order to integrate the PR in the master branch and proceed with the release and the packaging or, otherwise, we will skip this PR to perform the release.

**Comment by jose-sanchezm** [comment]
Unfortunately due to an injury I'm at home and I won't be able to work on it in time for the release. It can be released in a future update for the Release 2. I will work on it as soon as I get back to work.
Sorry for the inconvenience.

**Comment by dealfonso** [comment]
Hi @jose-sanchezm,

it seems to be properly working, but the tests are only for ONE4. In ONE5 onevm shutdown does not work. The corresponding command is onevm terminate.

Please correct it and it will be ready to merge.

**Pull request merged**
